name: HelloWorld
on: workflow_dispatch
jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
     - name: Hellostep
       run: |
        echo "sai"
        echo "welcome"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: new-task
        run: echo "this is 2nd job"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy-task
        run: |
         echo "new-deployment"
         echo "This new task"
